name: Publish to npm on push to main

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.actor != 'fdk-bot'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps

      - name: Run tests
        run: |
          if yarn run -T test -v >/dev/null 2>&1; then
            yarn test --run
          else
            echo "No tests configured, skipping"
          fi

      - name: Build package
        run: yarn build

      - name: Configure git user
        run: |
          git config user.name "fdk-bot"
          git config user.email "fdk-bot@users.noreply.github.com"

      - name: Bump version (patch) and create tag
        run: |
          npm version patch -m "ci: release %s"

      - name: Check if version already exists on npm
        id: check_version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOT_TOKEN }}
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")

          if npm view "${PACKAGE_NAME}@${CURRENT_VERSION}" version >/dev/null 2>&1; then
            echo "Version ${CURRENT_VERSION} already exists on npm"
            echo "should_publish=false" >> $GITHUB_OUTPUT
          else
            echo "Version ${CURRENT_VERSION} does not exist on npm, proceeding with publish"
            echo "should_publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        if: steps.check_version.outputs.should_publish == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOT_TOKEN }}
        run: |
          if npm publish --access public; then
            echo "✅ Package published successfully"
          else
            echo "❌ npm publish failed, rolling back git tag"
            git tag -d "v$(node -p "require('./package.json').version")"
            exit 1
          fi

      - name: Push changes and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git push origin HEAD:main --follow-tags; then
            echo "✅ Changes and tags pushed successfully"
          else
            echo "❌ Failed to push changes to repository"
            # Don't exit with error if npm publish was skipped
            if [[ "${{ steps.check_version.outputs.should_publish }}" == "false" ]]; then
              echo "⚠️ Git push failed, but npm publish was skipped (version already exists)"
              echo "You may need to manually sync the repository state"
            else
              exit 1
            fi
          fi
