name: Publish to npm on push to main

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.actor != 'fdk-bot'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: |
          if yarn run -T test -v >/dev/null 2>&1; then
            yarn test --run
          else
            echo "No tests configured, skipping"
          fi

      - name: Build package
        run: yarn build

      - name: Configure git user
        run: |
          git config user.name "fdk-bot"
          git config user.email "fdk-bot@users.noreply.github.com"

      - name: Bump version (patch) and create tag
        run: |
          npm version patch -m "ci: release %s"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOT_TOKEN }}
        run: |
          if npm publish --access public; then
            echo "✅ Package published successfully"
          else
            echo "❌ npm publish failed, rolling back git tag"
            git tag -d "v$(node -p "require('./package.json').version")"
            exit 1
          fi

      - name: Push changes and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git push origin HEAD:main --follow-tags; then
            echo "✅ Changes and tags pushed successfully"
          else
            echo "❌ Failed to push changes to repository"
            exit 1
          fi
